name: Build .NET Core
description: Builds a .NET Core project or solution

branding:
    icon: box

inputs:
    build-path:
        description: Path to project/solution/directory to build
        required: false
        default: ""
    configuration:
        description: Name of .NET project/solution configuration to use when building
        required: false
        default: Release
    run-tests:
        description: After building, runs any tests found in the project/solution/directory
        required: false
        default: true

runs:
    using: composite
    steps:
        - name: Restore
          shell: bash
          run: dotnet restore '${{ inputs.build-path }}'

        - name: Build
          shell: bash
          run: |
              dotnet build '${{ inputs.build-path }}' \
                --configuration ${{ inputs.configuration }} \
                --no-restore \
                -p:TreatWarningsAsErrors=true

        - name: Test
          if: inputs.run-tests == 'true'
          shell: bash
          run: |
              dotnet test '${{ inputs.build-path }}' \
                --configuration ${{ inputs.configuration }} \
                --no-build \
                --verbosity normal
